version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    secrets:
      - site_owner
      - firefly_app_key
      - firefly_db_password
    networks:
      - traefik-public
    depends_on:
      - db
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.portainer-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.portainer-http.entrypoints=http
        - traefik.http.routers.portainer-http.middlewares=https-redirect
        - traefik.http.routers.portainer-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.portainer-https.entrypoints=https
        - traefik.http.routers.portainer-https.tls=true
        - traefik.http.routers.portainer-https.tls.certresolver=le
        - traefik.http.services.portainer.loadbalancer.server.port=80
  db:
    image: mariadb
    hostname: db
    env_file: .db.env
    secrets:
      - firefly_db_password
    volumes:
      - firefly_iii_db:/var/lib/mysql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"

volumes:
  firefly_iii_upload:
  firefly_iii_db:


networks:
  traefik-public:
    external: true

secrets:
  site_owner:
    external: true
  firefly_db_password:
    external: true
  firefly_app_key:
    external: true
