apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ${name}
  namespace: ${flux_namespace}
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: kustomizations
  path: ./kustomizations/service
  postBuild:
    substitute:
      name: ${name}
      image: ${image}
      tag: latest # {"$imagepolicy": "flux-system:${name}:tag"}